# Generated by Django 4.1.1 on 2022-09-26 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_hobby_alter_person_id_reunion_person_hobbie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='hobbie',
            new_name='hobbies',
        ),
    ]
