# Generated by Django 4.1.1 on 2022-09-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Mi Autor', 'verbose_name_plural': 'Autores'},
        ),
    ]
