# Generated by Django 4.1.1 on 2022-09-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_alter_user_apellidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='codRegistro',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
