# Generated by Django 4.1 on 2022-08-30 13:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_empleado_habilidades'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habilidades',
            options={'verbose_name': 'Habilidad', 'verbose_name_plural': 'Habilidades'},
        ),
        migrations.AddField(
            model_name='empleado',
            name='hoja_vida',
            field=ckeditor.fields.RichTextField(default='texto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='last_name',
            field=models.CharField(max_length=60, verbose_name='Apellidos'),
        ),
    ]
