# Generated by Django 4.1.1 on 2022-09-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lector',
            options={'verbose_name': 'Mi Lector', 'verbose_name_plural': 'Lectores'},
        ),
        migrations.AlterModelOptions(
            name='prestamo',
            options={'verbose_name': 'Mi Prestamo', 'verbose_name_plural': 'Prestamos'},
        ),
    ]
