# Generated by Django 4.1.1 on 2022-09-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0003_alter_prestamo_libro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lector',
            name='nombre',
        ),
        migrations.AddField(
            model_name='lector',
            name='nombres',
            field=models.CharField(default='autor', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lector',
            name='edad',
            field=models.PositiveIntegerField(),
        ),
    ]
