# Generated by Django 4.1.1 on 2022-09-20 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contacto', 'verbose_name_plural': 'Contactos'},
        ),
    ]
